//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.4

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "todos")]
pub struct Model {
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(primary_key)]
    pub id: i32,
    pub todo: String,
    pub priority: i8,
    pub start_date: Date,
    pub end_date: Option<Date>,
    pub status_id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::statuses::Entity",
        from = "Column::StatusId",
        to = "super::statuses::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Statuses,
}

impl Related<super::statuses::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Statuses.def()
    }
}
